package com.filetransfer.web.analytics.repository;

import com.filetransfer.web.analytics.model.AnalyticsModels.BusinessIntelligenceReport;
import com.filetransfer.web.analytics.model.AnalyticsModels.ReportType;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Optional;

/**
 * Repository for Business Intelligence Reports
 * Manages pre-computed analytical reports and insights
 */
@Repository
public interface BusinessIntelligenceReportRepository extends JpaRepository<BusinessIntelligenceReport, Long> {

    /**
     * Find reports by tenant and report type
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = :reportType ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findByTenantIdAndReportType(@Param("tenantId") String tenantId, 
                                                                @Param("reportType") ReportType reportType);

    /**
     * Find reports by tenant, type and date range
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = :reportType AND bir.reportPeriodStart >= :startDate AND bir.reportPeriodEnd <= :endDate ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findByTenantIdAndReportTypeAndDateRange(@Param("tenantId") String tenantId, 
                                                                            @Param("reportType") ReportType reportType, 
                                                                            @Param("startDate") LocalDate startDate, 
                                                                            @Param("endDate") LocalDate endDate);

    /**
     * Find recent report (within specified time window)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = :reportType AND bir.reportPeriodStart = :periodStart AND bir.reportPeriodEnd = :periodEnd AND bir.generatedAt > :generatedAfter ORDER BY bir.generatedAt DESC")
    Optional<BusinessIntelligenceReport> findRecentReport(@Param("tenantId") String tenantId, 
                                                          @Param("reportType") ReportType reportType, 
                                                          @Param("periodStart") LocalDate periodStart, 
                                                          @Param("periodEnd") LocalDate periodEnd, 
                                                          @Param("generatedAfter") LocalDateTime generatedAfter);

    /**
     * Find latest report of each type for a tenant
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.id IN (SELECT MAX(bir2.id) FROM BusinessIntelligenceReport bir2 WHERE bir2.tenantId = :tenantId GROUP BY bir2.reportType) ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findLatestReportsByTenant(@Param("tenantId") String tenantId);

    /**
     * Find reports by tenant with pagination
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId ORDER BY bir.generatedAt DESC")
    Page<BusinessIntelligenceReport> findByTenantIdOrderByGeneratedAtDesc(@Param("tenantId") String tenantId, 
                                                                          Pageable pageable);

    /**
     * Find reports by multiple tenants (for multi-tenant analysis)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId IN :tenantIds AND bir.reportType = :reportType ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findByTenantIdsAndReportType(@Param("tenantIds") List<String> tenantIds, 
                                                                 @Param("reportType") ReportType reportType);

    /**
     * Find reports generated by specific user
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.createdBy = :createdBy ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findByTenantIdAndCreatedBy(@Param("tenantId") String tenantId, 
                                                               @Param("createdBy") String createdBy);

    /**
     * Find expired reports for cleanup
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.expiresAt IS NOT NULL AND bir.expiresAt < :currentTime")
    List<BusinessIntelligenceReport> findExpiredReports(@Param("currentTime") LocalDateTime currentTime);

    /**
     * Find large reports (by size) for optimization analysis
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.reportSizeBytes > :sizeThreshold ORDER BY bir.reportSizeBytes DESC")
    List<BusinessIntelligenceReport> findLargeReports(@Param("sizeThreshold") Long sizeThreshold);

    /**
     * Find slow-generating reports for performance analysis
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.generationTimeMs > :timeThreshold ORDER BY bir.generationTimeMs DESC")
    List<BusinessIntelligenceReport> findSlowReports(@Param("timeThreshold") Long timeThreshold);

    /**
     * Get report generation statistics
     */
    @Query("SELECT " +
           "bir.reportType, " +
           "COUNT(bir) as reportCount, " +
           "AVG(bir.generationTimeMs) as avgGenerationTime, " +
           "AVG(bir.reportSizeBytes) as avgReportSize, " +
           "MIN(bir.generatedAt) as oldestReport, " +
           "MAX(bir.generatedAt) as newestReport " +
           "FROM BusinessIntelligenceReport bir " +
           "WHERE bir.tenantId = :tenantId AND bir.generatedAt BETWEEN :startTime AND :endTime " +
           "GROUP BY bir.reportType " +
           "ORDER BY reportCount DESC")
    List<Object[]> getReportGenerationStatistics(@Param("tenantId") String tenantId, 
                                                 @Param("startTime") LocalDateTime startTime, 
                                                 @Param("endTime") LocalDateTime endTime);

    /**
     * Find reports for specific time period
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportPeriodStart <= :periodEnd AND bir.reportPeriodEnd >= :periodStart ORDER BY bir.reportPeriodStart ASC")
    List<BusinessIntelligenceReport> findReportsForPeriod(@Param("tenantId") String tenantId, 
                                                          @Param("periodStart") LocalDate periodStart, 
                                                          @Param("periodEnd") LocalDate periodEnd);

    /**
     * Find daily summary reports for trend analysis
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'DAILY_SUMMARY' AND bir.reportPeriodStart BETWEEN :startDate AND :endDate ORDER BY bir.reportPeriodStart ASC")
    List<BusinessIntelligenceReport> findDailySummaryReports(@Param("tenantId") String tenantId, 
                                                            @Param("startDate") LocalDate startDate, 
                                                            @Param("endDate") LocalDate endDate);

    /**
     * Find weekly summary reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'WEEKLY_SUMMARY' AND bir.reportPeriodStart BETWEEN :startDate AND :endDate ORDER BY bir.reportPeriodStart ASC")
    List<BusinessIntelligenceReport> findWeeklySummaryReports(@Param("tenantId") String tenantId, 
                                                             @Param("startDate") LocalDate startDate, 
                                                             @Param("endDate") LocalDate endDate);

    /**
     * Find monthly summary reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'MONTHLY_SUMMARY' AND bir.reportPeriodStart BETWEEN :startDate AND :endDate ORDER BY bir.reportPeriodStart ASC")
    List<BusinessIntelligenceReport> findMonthlySummaryReports(@Param("tenantId") String tenantId, 
                                                              @Param("startDate") LocalDate startDate, 
                                                              @Param("endDate") LocalDate endDate);

    /**
     * Find reports by name pattern (for custom reports)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportName LIKE :namePattern ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findByTenantIdAndReportNameLike(@Param("tenantId") String tenantId, 
                                                                    @Param("namePattern") String namePattern);

    /**
     * Count reports by type and tenant
     */
    @Query("SELECT COUNT(bir) FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = :reportType")
    long countByTenantIdAndReportType(@Param("tenantId") String tenantId, 
                                     @Param("reportType") ReportType reportType);

    /**
     * Get total storage used by reports for a tenant
     */
    @Query("SELECT COALESCE(SUM(bir.reportSizeBytes), 0) FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId")
    long getTotalReportStorageByTenant(@Param("tenantId") String tenantId);

    /**
     * Find reports that need regeneration (old or expired)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND (bir.expiresAt < :currentTime OR bir.generatedAt < :regenerateThreshold) ORDER BY bir.generatedAt ASC")
    List<BusinessIntelligenceReport> findReportsNeedingRegeneration(@Param("tenantId") String tenantId, 
                                                                   @Param("currentTime") LocalDateTime currentTime, 
                                                                   @Param("regenerateThreshold") LocalDateTime regenerateThreshold);

    /**
     * Find performance analysis reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'PERFORMANCE_ANALYSIS' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findPerformanceAnalysisReports(@Param("tenantId") String tenantId);

    /**
     * Find quality analysis reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'QUALITY_ANALYSIS' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findQualityAnalysisReports(@Param("tenantId") String tenantId);

    /**
     * Find cost analysis reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'COST_ANALYSIS' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findCostAnalysisReports(@Param("tenantId") String tenantId);

    /**
     * Find SLA compliance reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'SLA_COMPLIANCE' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findSlaComplianceReports(@Param("tenantId") String tenantId);

    /**
     * Find trend analysis reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'TREND_ANALYSIS' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findTrendAnalysisReports(@Param("tenantId") String tenantId);

    /**
     * Find predictive analysis reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'PREDICTIVE_ANALYSIS' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findPredictiveAnalysisReports(@Param("tenantId") String tenantId);

    /**
     * Find anomaly detection reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'ANOMALY_DETECTION' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findAnomalyDetectionReports(@Param("tenantId") String tenantId);

    /**
     * Find capacity planning reports
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.reportType = 'CAPACITY_PLANNING' ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findCapacityPlanningReports(@Param("tenantId") String tenantId);

    /**
     * Get report access statistics (most viewed reports)
     */
    @Query("SELECT bir.reportType, bir.reportName, COUNT(bir) as accessCount FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId AND bir.generatedAt BETWEEN :startTime AND :endTime GROUP BY bir.reportType, bir.reportName ORDER BY accessCount DESC")
    List<Object[]> getReportAccessStatistics(@Param("tenantId") String tenantId, 
                                            @Param("startTime") LocalDateTime startTime, 
                                            @Param("endTime") LocalDateTime endTime);

    /**
     * Find reports with generation errors (very short generation time might indicate error)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.generationTimeMs < :minTime OR bir.reportSizeBytes < :minSize ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findPotentiallyCorruptedReports(@Param("minTime") Long minTime, 
                                                                     @Param("minSize") Long minSize);

    /**
     * Get tenant activity summary based on report generation
     */
    @Query("SELECT " +
           "bir.tenantId, " +
           "COUNT(bir) as totalReports, " +
           "COUNT(DISTINCT bir.reportType) as uniqueReportTypes, " +
           "MAX(bir.generatedAt) as lastReportGenerated, " +
           "AVG(bir.generationTimeMs) as avgGenerationTime, " +
           "SUM(bir.reportSizeBytes) as totalStorageUsed " +
           "FROM BusinessIntelligenceReport bir " +
           "WHERE bir.generatedAt BETWEEN :startTime AND :endTime " +
           "GROUP BY bir.tenantId " +
           "ORDER BY totalReports DESC")
    List<Object[]> getTenantActivitySummary(@Param("startTime") LocalDateTime startTime, 
                                           @Param("endTime") LocalDateTime endTime);

    /**
     * Find duplicate reports (same tenant, type, and period)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE EXISTS (SELECT 1 FROM BusinessIntelligenceReport bir2 WHERE bir2.tenantId = bir.tenantId AND bir2.reportType = bir.reportType AND bir2.reportPeriodStart = bir.reportPeriodStart AND bir2.reportPeriodEnd = bir.reportPeriodEnd AND bir2.id != bir.id) ORDER BY bir.generatedAt DESC")
    List<BusinessIntelligenceReport> findDuplicateReports();

    /**
     * Get system-wide report generation metrics
     */
    @Query("SELECT " +
           "COUNT(bir) as totalReports, " +
           "COUNT(DISTINCT bir.tenantId) as uniqueTenants, " +
           "AVG(bir.generationTimeMs) as avgGenerationTime, " +
           "SUM(bir.reportSizeBytes) as totalStorageUsed, " +
           "MIN(bir.generatedAt) as oldestReport, " +
           "MAX(bir.generatedAt) as newestReport " +
           "FROM BusinessIntelligenceReport bir " +
           "WHERE bir.generatedAt BETWEEN :startTime AND :endTime")
    Object[] getSystemWideReportMetrics(@Param("startTime") LocalDateTime startTime, 
                                       @Param("endTime") LocalDateTime endTime);

    /**
     * Find reports for data archival (older than retention period)
     */
    @Query("SELECT bir FROM BusinessIntelligenceReport bir WHERE bir.generatedAt < :archivalDate ORDER BY bir.generatedAt ASC")
    List<BusinessIntelligenceReport> findReportsForArchival(@Param("archivalDate") LocalDateTime archivalDate);

    /**
     * Delete reports older than specified date
     */
    @Query("DELETE FROM BusinessIntelligenceReport bir WHERE bir.generatedAt < :cutoffDate")
    void deleteOldReports(@Param("cutoffDate") LocalDateTime cutoffDate);

    /**
     * Delete reports by tenant (for tenant cleanup)
     */
    @Query("DELETE FROM BusinessIntelligenceReport bir WHERE bir.tenantId = :tenantId")
    void deleteReportsByTenant(@Param("tenantId") String tenantId);
}