package com.filetransfer.web.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * Entity representing HSM validation records for tracking cryptographic operations
 */
@Entity
@Table(name = "hsm_validation_records")
public class HsmValidationRecord {
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    
    @Column(nullable = false)
    private Long fileTransferId; // Reference to the file transfer record
    
    @Column(nullable = false)
    private String fileName;
    
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private HsmProvider hsmProvider;
    
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private HsmOperation operation;
    
    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private HsmValidationStatus status;
    
    @Column(nullable = false)
    private String tenantId;
    
    @Column(nullable = false)
    private String serviceName;
    
    @Column
    private String subServiceName;
    
    @Column(name = "hsm_key_id")
    private String hsmKeyId; // HSM key identifier
    
    @Column(name = "hsm_key_alias")
    private String hsmKeyAlias; // HSM key alias/label
    
    @Column(name = "algorithm")
    private String algorithm; // Cryptographic algorithm used
    
    @Column(name = "signature_value", columnDefinition = "TEXT")
    private String signatureValue; // Digital signature or hash value
    
    @Column(name = "original_hash")
    private String originalHash; // Original file hash before HSM operation
    
    @Column(name = "hsm_hash")
    private String hsmHash; // Hash generated by HSM
    
    @Column(name = "validation_data", columnDefinition = "TEXT")
    private String validationData; // Additional validation data (certificates, etc.)
    
    @Column(name = "error_message", columnDefinition = "TEXT")
    private String errorMessage;
    
    @Column(name = "error_code")
    private String errorCode;
    
    @Column(nullable = false)
    private LocalDateTime createdAt;
    
    @Column
    private LocalDateTime startedAt;
    
    @Column
    private LocalDateTime completedAt;
    
    @Column(name = "processing_time_ms")
    private Long processingTimeMs;
    
    @Column(name = "hsm_session_id")
    private String hsmSessionId; // HSM session identifier
    
    @Column(name = "certificate_serial")
    private String certificateSerial; // Certificate serial number if applicable
    
    @Column(name = "key_version")
    private Integer keyVersion; // HSM key version
    
    @Column(name = "metadata", columnDefinition = "TEXT")
    private String metadata; // Additional metadata as JSON
    
    // Constructors
    public HsmValidationRecord() {
        this.createdAt = LocalDateTime.now();
        this.status = HsmValidationStatus.PENDING;
    }
    
    public HsmValidationRecord(Long fileTransferId, String fileName, String tenantId, 
                             String serviceName, String subServiceName, 
                             HsmProvider hsmProvider, HsmOperation operation) {
        this();
        this.fileTransferId = fileTransferId;
        this.fileName = fileName;
        this.tenantId = tenantId;
        this.serviceName = serviceName;
        this.subServiceName = subServiceName;
        this.hsmProvider = hsmProvider;
        this.operation = operation;
    }
    
    // Getters and Setters
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    
    public Long getFileTransferId() { return fileTransferId; }
    public void setFileTransferId(Long fileTransferId) { this.fileTransferId = fileTransferId; }
    
    public String getFileName() { return fileName; }
    public void setFileName(String fileName) { this.fileName = fileName; }
    
    public HsmProvider getHsmProvider() { return hsmProvider; }
    public void setHsmProvider(HsmProvider hsmProvider) { this.hsmProvider = hsmProvider; }
    
    public HsmOperation getOperation() { return operation; }
    public void setOperation(HsmOperation operation) { this.operation = operation; }
    
    public HsmValidationStatus getStatus() { return status; }
    public void setStatus(HsmValidationStatus status) { this.status = status; }
    
    public String getTenantId() { return tenantId; }
    public void setTenantId(String tenantId) { this.tenantId = tenantId; }
    
    public String getServiceName() { return serviceName; }
    public void setServiceName(String serviceName) { this.serviceName = serviceName; }
    
    public String getSubServiceName() { return subServiceName; }
    public void setSubServiceName(String subServiceName) { this.subServiceName = subServiceName; }
    
    public String getHsmKeyId() { return hsmKeyId; }
    public void setHsmKeyId(String hsmKeyId) { this.hsmKeyId = hsmKeyId; }
    
    public String getHsmKeyAlias() { return hsmKeyAlias; }
    public void setHsmKeyAlias(String hsmKeyAlias) { this.hsmKeyAlias = hsmKeyAlias; }
    
    public String getAlgorithm() { return algorithm; }
    public void setAlgorithm(String algorithm) { this.algorithm = algorithm; }
    
    public String getSignatureValue() { return signatureValue; }
    public void setSignatureValue(String signatureValue) { this.signatureValue = signatureValue; }
    
    public String getOriginalHash() { return originalHash; }
    public void setOriginalHash(String originalHash) { this.originalHash = originalHash; }
    
    public String getHsmHash() { return hsmHash; }
    public void setHsmHash(String hsmHash) { this.hsmHash = hsmHash; }
    
    public String getValidationData() { return validationData; }
    public void setValidationData(String validationData) { this.validationData = validationData; }
    
    public String getErrorMessage() { return errorMessage; }
    public void setErrorMessage(String errorMessage) { this.errorMessage = errorMessage; }
    
    public String getErrorCode() { return errorCode; }
    public void setErrorCode(String errorCode) { this.errorCode = errorCode; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public LocalDateTime getStartedAt() { return startedAt; }
    public void setStartedAt(LocalDateTime startedAt) { this.startedAt = startedAt; }
    
    public LocalDateTime getCompletedAt() { return completedAt; }
    public void setCompletedAt(LocalDateTime completedAt) { this.completedAt = completedAt; }
    
    public Long getProcessingTimeMs() { return processingTimeMs; }
    public void setProcessingTimeMs(Long processingTimeMs) { this.processingTimeMs = processingTimeMs; }
    
    public String getHsmSessionId() { return hsmSessionId; }
    public void setHsmSessionId(String hsmSessionId) { this.hsmSessionId = hsmSessionId; }
    
    public String getCertificateSerial() { return certificateSerial; }
    public void setCertificateSerial(String certificateSerial) { this.certificateSerial = certificateSerial; }
    
    public Integer getKeyVersion() { return keyVersion; }
    public void setKeyVersion(Integer keyVersion) { this.keyVersion = keyVersion; }
    
    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }
    
    /**
     * Check if this validation has timed out
     */
    public boolean hasTimedOut(int timeoutMinutes) {
        if (startedAt == null || completedAt != null) {
            return false;
        }
        return LocalDateTime.now().isAfter(startedAt.plusMinutes(timeoutMinutes));
    }
    
    /**
     * Calculate processing duration
     */
    public Long calculateProcessingDuration() {
        if (startedAt == null || completedAt == null) {
            return null;
        }
        return java.time.Duration.between(startedAt, completedAt).toMillis();
    }
    
    /**
     * Get validation summary for display
     */
    public String getValidationSummary() {
        StringBuilder summary = new StringBuilder();
        summary.append(operation.getDisplayName())
               .append(" using ")
               .append(hsmProvider.getDisplayName())
               .append(" - ")
               .append(status.getDisplayName());
        
        if (processingTimeMs != null) {
            summary.append(" (").append(processingTimeMs).append("ms)");
        }
        
        return summary.toString();
    }
}